---

- name: "Check whether the node exporter has already been installed"
  stat:
    path: "{{ node_exporter_path }}node_exporter"
    checksum_algorithm: "{{ node_exporter_checksum_algorithm }}"
  register: "bin"

- name: "Fetch the archive from GitHub"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    checksum: "{{ node_exporter_checksum_algorithm }}:{{ node_exporter_checksum_archive }}"
  when: bin.stat.exists == False or
        bin.stat.checksum != node_exporter_checksum_binary

- name: "Unpack the archive in /tmp"
  unarchive:
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    dest: "/tmp"
  when: bin.stat.exists == False or
        bin.stat.checksum != node_exporter_checksum_binary

- name: "Move node-exporter to the {{ node_exporter_path }}node_exporter"
  copy:
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_path }}node_exporter"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=rwx"
  when: bin.stat.exists == False or
        bin.stat.checksum != node_exporter_checksum_binary
  notify: "restart node_exporter"


- name: "Clean the /tmp/ dir up"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    - "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/"
  when: bin.stat.exists == False or
        bin.stat.checksum != node_exporter_checksum_binary